runtime: php74

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /js
  static_dir: /js

- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))

- url: /.*
  script: index.php